VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clGKPZ"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'Public sInvProjName As String 'Наименование инв.проекта (стлб. 2)
'Public sInvProjID As String 'Идентификатор инв.проекта (стлб. 3)
'Public sPurchProd As String 'Наименование закупаемой продукции (стлб 12)
'Public sOrg As String 'Организатор закупки (стлб 13)
'Public sPlPrice As String 'Планируемая цена закупки (стлб 14)
'Public sPurchMethod As String 'Планируемый способ закупки (стлб 16)
'Public sNoticePlDate As String 'Планируемая дата объявления ЗП (стлб 17)
'Public sSignPlDate As String 'Планируема дата заключения договора (стлб 18)
'Public sStartPlDate As String 'Планируемая дата начала поставки/работ (стлб 19)
Public sPosition As String 'Заявка/Позиция (стлб 21)



